---
- hosts: master-node,data1-warm-node,data2-cold-node,data3-hot-node,data4-hot-node,coordinating-node
  gather_facts: true
  remote_user: admin
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
  roles:
    - elasticsearch

- hosts: kibana
  gather_facts: true
  remote_user: admin
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
  roles:
    - kibana

- hosts: logstash
  gather_facts: true
  remote_user: admin
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
  roles:
    - {role: logstash, version: 7.16.3}
