---
- hosts: all
  gather_facts: true
  become: yes
  roles:
    - role: upgrade_packages
    - role: node_exporter
    - role: kernel_tuning
    - {role: create_users, username: 'example', uid: '1234', gid: '1234', additional_groups: ['sudo'], sudoer: 'yes'}
    - {role: docker, docker_users: ['example']}
